spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/sk_example_db
    password: 11111111
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log:
        db/changelog/changelog-master.yaml
server:
  port: 8080
